# Generated by Django 4.2.7 on 2024-01-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_blog', '0003_article_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
