# Generated by Django 4.2.7 on 2024-01-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_blog', '0004_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post_author',
            new_name='author',
        ),
    ]
