# Generated by Django 4.2.7 on 2023-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teacategory_options_teacategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaproduct',
            name='in_stock',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
    ]
