# Generated by Django 4.2.7 on 2023-11-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teaproduct_in_stock_alter_teacategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaproduct',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='teaproduct',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
