# Generated by Django 4.2.7 on 2023-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teaproduct_options_teaproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaproduct',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
