# Generated by Django 4.2.7 on 2023-12-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_teaproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/types/'),
        ),
        migrations.AlterField(
            model_name='teaproduct',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/tea/', verbose_name='Image path'),
        ),
    ]
