# Generated by Django 4.2.7 on 2024-01-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_teacategory_image_alter_teaproduct_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10)),
                ('version_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teaproduct')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'unique_together': {('product', 'version_name')},
            },
        ),
    ]
