# Generated by Django 4.2.7 on 2024-01-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_version_text_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('product', 'version_number')},
        ),
    ]
